### ISSUE TITLE
Some filters are slow (e.g. gamma correction)

### ISSUE THREAD

**Issue by jetic83** [usnistgov/OpenSeadragonFiltering#10]
I love this filter plugin, thank you!

I encountered some filters to be slow and have a solution for this.

E.g. gamma filter:
Instead of calculating every pixel with the Math.pow function, (which can be 256x256x3 calculations per tile), all very similar, only changing in the pixel value, which can be 0-255), precompute the gamma change for all possible 256 values, and then just choose the right one for a given pixel.

This precomputation can even be used globally for all tiles, and only has be changed if the filter options are newly set.

A test showed that this drastically speeds up the filter.

I work on a pull request for that.

**Comment by jetic83** [comment]
pull request #11 created.

**Comment by avandecreme** [comment]
Thanks again for the PR.
