### ISSUE TITLE
plugin shows this warning multiple times, is there any fix for it?

### ISSUE THREAD

**Issue by sinamcr7** [usnistgov/OpenSeadragonFiltering#30]
the warning is this
Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: <URL>

I tried to put { willReadFrequently: true } in all getImageData calls but its still same

**Comment by msalsbery** [comment]
> the warning is this
> 
> Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: <URL>
> 
> 
> 
> I tried to put { willReadFrequently: true } in all getImageData calls but its still same

The flag should be used on the getContext() calls, no?

**Comment by sinamcr7** [comment]
thank you, its fixed now
