### ISSUE TITLE
Update for new OSD?

### ISSUE THREAD

**Issue by iangilman** [usnistgov/OpenSeadragonFiltering#5]
I could be wrong, but instead of tile._renderedContext, now we need to use tile.context2D here: 

https://github.com/usnistgov/OpenSeadragonFiltering/blob/master/openseadragon-filtering.js#L91

**Comment by avandecreme** [comment]
`tile._renderedContext` is an internal variable of this plugin.
I explained in little bit more details there: https://github.com/openseadragon/openseadragon/issues/1084

**Comment by iangilman** [comment]
Gotcha. Just confused by the naming, I suppose :-) Thanks for the clarification!
