### ISSUE TITLE
demo-bundle.js returns HTTP 404 and Uncaught Reference Error

### ISSUE THREAD

**Issue by imoutsatsos** [usnistgov/OpenSeadragonFiltering#9]
First, thank you for the development of this very useful plugin! I cloned the repository to a web server and tried to access the index.html
However, the demo-bundle.js referenced in the index.html does not appear to be in the repository and results in a 404 error. However, a demo.js exists and I suspect that this is what the index.html should reference.

Nonetheless, if you replace 'demo-bundle' with 'demo' you now get another error 
```
 Uncaught ReferenceError: require is not defined
    at demo.js:18
```

Perhaps you can document what other packages are required for the installation of this OSD plugin.
Thank you!

**Comment by avandecreme** [comment]
The demo is accessible here: https://pages.nist.gov/OpenSeadragonFiltering/

If you want to build it yourself, you must run `npm install` which will create the demo-bundle.js file.

**Comment by imoutsatsos** [comment]
Thank you for looking into this. Unfortunately following the instructions you provided I still can't build this on a Windows x64 platform. The `npm install` finished with a warning (see below) that may be affecting the build, but nonetheless, I still do not see the `demo-bundle.js` file being generated.

![image](https://user-images.githubusercontent.com/3408226/26905029-e56e5646-4bb2-11e7-8da5-5e1c543dc6fd.png)

**Comment by rmd13** [comment]
> Thank you for looking into this. Unfortunately following the instructions you provided I still can't build this on a Windows x64 platform. The `npm install` finished with a warning (see below) that may be affecting the build, but nonetheless, I still do not see the `demo-bundle.js` file being generated.
> 
> ![image](https://user-images.githubusercontent.com/3408226/26905029-e56e5646-4bb2-11e7-8da5-5e1c543dc6fd.png)

Hi, I get demo-bundle by checking the source code in explorer and click the reference for demo-bundle.js, then I get the full text of this file in explorer. Just save it.
